### ISSUE TITLE
Doesn't work with Maya 2023?

### ISSUE THREAD

**Issue by byungiljung** [swnolan/metahuman_facial_transfer#1]
I would really appreciate it if you could update it to work in Maya 2023 as well.

**Comment by swnolan** [comment]
Do you mind

**Comment by swnolan** [comment]
Do you mind providing more information other than it doesn't work?

**Comment by swnolan** [comment]
Argh, sorry, didn't mean to close this! Started a new ticket

**Comment by swnolan** [comment]
There seems to be an FBX incompatibility between Maya 2022 and 2023.  Bring in the FBX sample into Maya 2023, the keyframes are gone. For now, until I can search down a cause of this, the code does work in Maya 2022 and that's all this code can support at the moment. Apologies for the inconvenience.
