### ISSUE TITLE
Cannot import the drag and drop into maya 2022 or 2023

### ISSUE THREAD

**Issue by Arnaudl31** [swnolan/metahuman_facial_transfer#11]
Hey There, i have an error when i drag and drop the python files from my scripts folder.

script editor error : # Error: SameFileError: file C:\Program Files\Autodesk\Maya2023\Python\lib\shutil.py line 244: 'C:\\Users/Arnaud501/Documents/maya/2023/scripts\\metahuman_api.py' and 'C:/Users/Arnaud501/Documents/maya/2023/scripts/metahuman_api.py' are the same fil

if you have a solution ^^

Thanks !

**Comment by swnolan** [comment]
Hi, thanks for reporting. Will get that fixed up quickly.

**Comment by swnolan** [comment]
Closing as recent update addresses issue.

**Comment by Arnaudl31** [comment]
Thank you very much =) 

i realized that writing in the shelf editor the old command to call the script work :  import metahuman_facial_transfer
metahuman_facial_transfer.UI()

happy to see it's fixed !

**Comment by pepepepe4123** [comment]
Hi, every time I use 'drag and drop' in Maya, I get that error and it doesn't run. How do I fix it?

import maya.app.general.executeDroppedPythonFile as myTempEDPF
myTempEDPF.executeDroppedPythonFile("C:/Users/ghkdd/Downloads/metahuman_facial_transfer-main/metahuman_facial_transfer-main/drag_and_drop_install.py", "")
del myTempEDPF
# Error: invalid syntax
# Traceback (most recent call last):
# File "<maya console>", line 2, in <module>
# File "D:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\maya\app\general\executeDroppedPythonFile.py", line 66, in executeDroppedPythonFile
# loadedModule = imp.load_module(theModuleName, fp, pathname, desc)
# File "C:/Users/ghkdd/Downloads/metahuman_facial_transfer-main/metahuman_facial_transfer-main\drag_and_drop_install.py", line 43
# print(f'{api_file} is identical to {scripts_folder}\{api_file}\nSkipping...')
# ^
# SyntaxError: invalid syntax #

**Comment by swnolan** [comment]
Hi,
Just submitted and tested a fix for this for 2020 Python 2.7.
Download the new code and give it another go.
Cheers,
-Sean

________________________________

**Comment by pepepepe4123** [comment]
You saved my life! Thank you very much.

2024년 7월 25일 (목) 오전 8:17, Sean Nolan ***@***.***>님이 작성:

**Comment by swnolan** [comment]
You’re kindly welcome! I’m glad your life was spared.
________________________________
