### ISSUE TITLE
Error when I import another fbx file

### ISSUE THREAD

**Issue by mhwu2017** [swnolan/metahuman_facial_transfer#12]
Hi, first of all thank you for your scripts, it helps me a lot.

When I first use it to import an fbx animation, it works fine, but when I try to import another fbx file into the same maya project, an extra head appears. When I reopen the maya file, the import returns to normal. How can I solve this problem?

!
![POPO-20240912-151402](https://github.com/user-attachments/assets/74b182d8-887d-411c-adc0-fb18173bc745)

**Comment by swnolan** [comment]
Hi,
I suspect you are running into an error where there's already keyframes on the face controls and the FBX import process requires the need to make some direct connections to these controls and it errors out, leaving the FBX file in the scene.

For now, the best way to solve this is to use the "Select Facial Controls" and delete existing keyframes on the controls before importing a new FBX. I'll try and find the time to automate this step in a future update.

**Comment by mhwu2017** [comment]
> Hi, I suspect you are running into an error where there's already keyframes on the face controls and the FBX import process requires the need to make some direct connections to these controls and it errors out, leaving the FBX file in the scene.
> 
> For now, the best way to solve this is to use the "Select Facial Controls" and delete existing keyframes on the controls before importing a new FBX. I'll try and find the time to automate this step in a future update.

Apologies for the delayed response. The issue has been resolved using the method you provided. Thank you very much for your assistance.
