### ISSUE TITLE
CTRL_C_mouth not importing animation

### ISSUE THREAD

**Issue by imjeco** [swnolan/metahuman_facial_transfer#5]
First of all thank you for this tool, everything is working great but the "CTRL_C_mouth" controller that controls the overall position of the mouth doesn't seem to be receiving animation in maya. In metahuman animator inside unreal I can see the controller move but then when I use the tool to import the animation to the maya version of the rig, that controller doesn't move at all. I believe this is the only one that is not importing properly, at least I haven't noticed any issues other than this. I'm using maya 2022.2.

**Comment by swnolan** [comment]
Hi, apologies for the delay. Work work. I did update the import logic recently to handle some negative control values not being set. I'll take a look at this specific control and a few other TX and TY controls to make sure they match what's in UE. I have Maya 2022.5 and 2023 to test so won't be able to test 2022.2. I'll report back findings when possible. Appreciate the patience.

**Comment by swnolan** [comment]
I've tested using Maya 2022.5, Unreal 5.2 and downloaded the latest code and I get the same results from both UE and Maya. Maybe updating your cut from 2022.2 to .5 is what you need. 

![Maya2022_5_control_animation](https://github.com/swnolan/metahuman_facial_transfer/assets/7576862/a03057c4-9701-4572-a166-07a1dcfb589a)

**Comment by swnolan** [comment]
This is the exported animation sequence from Unreal I used to import into maya for you try and test. 
Unzip and import using the import sequence button from the tool.

[Face_Archetype_Skeleton_Sequence.zip](https://github.com/swnolan/metahuman_facial_transfer/files/12431236/Face_Archetype_Skeleton_Sequence.zip)

**Comment by imjeco** [comment]
Hey Sean, thanks for the reply. I just tested it again on the same maya version but using your exported sequence and it worked fine! So the issue seems to be coming from my exported animations, I'll try to figure out what is causing it and follow up here.

**Comment by imjeco** [comment]
The issue seems to be something with my metahumans, I just tested exporting the animation from the metahuman sample project and everything worked fine so there's something wrong with the metahuman I used to record/export the animation. Thanks for your time regardless, marking this as closed
