### ISSUE TITLE
Error when importing FBX (Maya 2023.3)

### ISSUE THREAD

**Issue by frederik-floor** [swnolan/metahuman_facial_transfer#6]
Hi! I'm getting an error when importing both from Animation Sequence and from Level Sequence. The latter works fine in Maya 2022.5, but not in 2023.3, which is unfortunate for our pipeline.

**Import FBX Level Sequence File:**
"Transfer failed! Missing animation data. Possible incompatible FBX data."
The script log says "File read in 1.5 seconds.", but then it gives 163 lines of this:
"// Warning: file: C:/Program Files/Autodesk/Maya2023/scripts/others/TimeSliderMenu.mel line 413: No objects selected to copy keys"
(The same FBX works in 2022.5).

Any help would be greatly appreciated in our tight deadline 😅❤️ This script is a lifesaver when it works!

**Comment by swnolan** [comment]
Hi Fredrik,
Might want to double check your FBX export settings from Unreal and make sure the "FBX Export Compatibility" is set to "FBX 2020". 

Here is a link to a few sample FBXs that I just tested in a vanilla Maya 2023.3 with a default Metahuman (Taro).
 
[https://drive.google.com/drive/folders/1uZLAlKcT8gB8-6y8GkLfRFa7k-cvnB_N?usp=drive_link](https://drive.google.com/drive/folders/1uZLAlKcT8gB8-6y8GkLfRFa7k-cvnB_N?usp=drive_link)

Here's the results I got with latest code.

<img width="1049" alt="Maya_2023 3" src="https://github.com/swnolan/metahuman_facial_transfer/assets/7576862/80679d02-8414-4692-9446-95ef73f38e17">

**Comment by swnolan** [comment]
Glad to hear it's been helpful otherwise 😄.

**Comment by frederik-floor** [comment]
Thanks for checking out this issue. I'm not sure what the problem is on my PC, but the script works on the same FBX on a different PC at the office.

**Comment by frederik-floor** [comment]
Actually, it would be helpful with a guide on how to correctly and completely uninstall this script. Maybe it'll help to do a fresh install of it.

**Comment by swnolan** [comment]
Down load latest code, unzip and use the drag and drop python file into your viewport. Follow the prompts and you should get a dialog with "Install updated". Existing code will be updated in your documents/maya/2023/scripts folder.

**Comment by frederik-floor** [comment]
Thanks! Turns out I had to delete all Maya preferences (Documents/maya) and then install your script again. Works perfectly now 😊
