### ISSUE TITLE
Closing the maya session and reopening causes issues

### ISSUE THREAD

**Issue by aluminal** [swnolan/metahuman_facial_transfer#9]
Hello!
I am able to import the facial animation from unreal to maya perfectly using this script. The issue I'm seeing is that if I save that file or save as in a new location, close the current maya session and reopen; there are some problems. If I select a metahuman control and try to set the current metahuman I now get an error "Missing critical node, embeddedNodeRL4, used for rig logic!". Also as I scrub through the timeline, the facial controls move, but have no influence on the mesh. Just wanted to check if you are seeing this behavior. I can also provide more detailed repo steps if necessary. 
Thank you for providing this script and updating it, it's honestly quite amazing.

**Comment by swnolan** [comment]
Hi,
I've not experienced this. 
Possibly the DNA file path is invalid or missing?

In your python script editor, to find the node, run this and it should select the node
```
import pymel.core as pm
embedded_node = pm.ls(type=pm.nt.EmbeddedNodeRL4)
pm.select(embedded_node, r=True)
```
In the attribute editor, make sure it points to the correct DNA path.
Btw, if you move this file, it won't update in the maya scene.

**Comment by aluminal** [comment]
Thank you! It was definitely an issue with the DNA path. I was able to fix the issue by first opening maya and then opening the maya scene; instead of double clicking to open the file directly. 
Thanks for the tip and thanks again for all your work on this script!
